test_site/urls.py
import settings
from django.conf.urls import url, include
from django.views.static import serve
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
]

users/urls.py
from django.conf.urls import url
from views import CursesView, UsersView, delete_user, create_user, change_user

urlpatterns = [
    url(r'^$', UsersView, name='users'),
    url(r'^courses/$', CursesView, name='courses'),
    url(r'^delete/', delete_user, name='delete'),
    url(r'^create/$', create_user, name='create'),
    url(r'^change/', change_user, name='change')
]

users/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

users/views.py
import json

from django.shortcuts import render
from django.db import connection
from django.http import Http404, HttpResponse

# Create your views here.

def run_procedure(proc_name, *args):
    cursor = connection.cursor()
    cursor.execute("call {0}({1});".format(proc_name, 
                                           ','.join([str(i) for i in args])))
    result = cursor.fetchall()
    cursor.close()

    return result

def CursesView(request):
    context = {
        "Courses": run_procedure("get_curses_list")
    }

    return render(request, 'users/courses.html', context)

def UsersView(request): 
    if ('page' not in request.GET) or ( not request.GET['page']):
        page = 1
    else:
        page = int(request.GET['page']) 
    if ('num_of_elements' not in request.GET)  \
       or (not request.GET['num_of_elements']):
        num_of_elements = 1
    else:
        num_of_elements = int(request.GET['num_of_elements'])
    offset = 0 if page == 1 else num_of_elements * (page-1)
    if ('name' in request.GET) and (request.GET['name']):
        users_num = run_procedure('get_users_number_name','"' 
                                  +  request.GET['name'] + '"')[0][0]
        users = run_procedure('get_users_by_name', num_of_elements, 
                              offset, '"' + request.GET['name'] + '"')
    else:
        users_num = run_procedure('get_users_number')[0][0]
        users = run_procedure('get_users_list', num_of_elements, offset)
    num_of_pages =   users_num / num_of_elements
    if users_num % num_of_elements > 0:
        num_of_pages += 1
    if page > num_of_pages:
        page = 1 
    context = {
        "Users": users,
        "pages": range(1, num_of_pages + 1),
        "num_of_pages": num_of_pages,
        "curr_page":  page,
        "num_of_elements": num_of_elements
    }

    return render(request, 'users/users.html', context)

def delete_user(request):
    if request.POST and request.is_ajax():
        run_procedure('delete_user', int(request.POST['user_id']))
        context = {
            "success": True
        }
        
        return HttpResponse(json.dumps(context), content_type='application/json')
    else:
        raise Http404

def create_user(request):
    if not request.POST:
        
       return render(request, 'users/create_user.html')
    elif request.is_ajax():
       name = '"' + request.POST['name'] + '"'
       email = '"' + request.POST['email'] + '"'
       phone = '"' + request.POST['phone'] + '"'
       mobilephone = '"' + request.POST['mobilephone'] + '"'
       status = '"' + request.POST['status'] + '"'
       run_procedure('create_user', name, email, phone, mobilephone, status)
       context = {
           "success": True
       }
       
       return HttpResponse(json.dumps(context), content_type='application/json')

def change_user(request): 
    if not request.POST: 
       user_id = int(request.GET['user_id'])
       user = run_procedure('get_user', user_id)
       context = {
           'user_id': user_id,
           'name': user[0][1],
           'email': user[0][2],
           'phone': user[0][3],
           'mobilephone': user[0][4],
           'status': user[0][5],
           'status_options': ['Active', 'Inactive']
       }

       return render(request, 'users/change_user.html', context)
    elif request.is_ajax():
        user_id = int(request.POST['user_id'])
        email = '"' + request.POST['email'] + '"'
        phone = '"' + request.POST['phone'] + '"'
        mobilephone = '"' + request.POST['mobilephone'] + '"'
        status = '"' + request.POST['status'] + '"'
        run_procedure('update_user', user_id, email, phone, mobilephone, status)
        context = {
            "success": True
        }

        return HttpResponse(json.dumps(context), content_type='application/json')

users/templates/users/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"></link>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css"></link>
        <script type="text/javascript" src="/media/jquery-3.0.0.min.js"></script>
        <script type="text/javascript" src="/media/main.js"></script>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <table style="width:100%; border-collapse:collapse">
            <thead>
                <th style="background-color: black; color: white">Test For You</th>
                <th style="background-color: black; text-align: right">
                    <a href="{% url 'users:users' %}" style="color:white; text-decoration:none">Users</a>
                </th>
                <th style="background-color: black;  text-align: left">
                    <a href="{% url 'users:courses' %}" style="color:white; text-decoration:none">Courses</a>
                </th>
            </thead>
        </table>
        {% block content %}{% endblock %}
        <footer style="bottom:0; position:fixed; width:100%; margin:auto">
            {% block footer %}{% endblock %}
        </footer>
    </body>
</html>

users/templates/users/change_user.html
<html>
    <head>
        <script type="text/javascript" src="/media/jquery-3.0.0.min.js"></script>
        <script type="text/javascript" src="/media/main.js"></script>            
        <title>
            Change User
        </title>
    </head>
    <body>
        <div style="width:100%; text-align:center">
            <input id="message" style="float:right; -webkit-border-radius: 10px; border-color:green; color:green" value="Changes saved">
            <a href="{% url 'users:users'%}" style="float:left"><img src="/media/back-icon.png"></a>
            <span style="font-size:xx-large;">Change User</span>
            <form id="change_form" action="http://127.0.0.1:8000/users/change/">
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{user_id}}">
                Name:<br>
                <input type="text" name="name" style="-webkit-border-radius: 10px;" pattern="[A-Za-z]+" oninput="this.setCustomValidity('')" oninvalid="this.setCustomValidity('This is required field. Only alphabetical symbols are allowed')" required disabled value="{{name}}">
                <br>
                E-Mail:<br>
                <input type="email" name="email" style="-webkit-border-radius: 10px;" oninput="this.setCustomValidity('')" oninvalid="this.setCustomValidity('This is required field. Email should be correct (example: aaa@fdd.com)')" required value="{{email}}">
                <br>
                Phone:<br>
                <input type="text" name="phone" style="-webkit-border-radius: 10px;" pattern="380\d{9}" oninput="this.setCustomValidity('')" oninvalid="this.setCustomValidity('Invalid number. Example 3080925057633')" value="{{phone}}">
                <br>
                Mobilephone:<br>
                <input type="text" name="mobilephone" style="-webkit-border-radius: 10px;" pattern="380\d{9}" oninput="this.setCustomValidity('')" oninvalid="this.setCustomValidity('Invalid number. Example 3080925057633')" value="{{mobilephone}}">
                <br>
                Status:<br>
                <select name="status">
                    {% for opt in status_options %}
                        {% ifequal opt status %}
                            <option class="selected">{{opt}}</option>
                        {% else %}
                            <option>{{opt}}</option>
                        {% endifequal %}
                    {% endfor %}
                </select>
                <br>
                <input type="submit" value="Save" style="background-color: green; color: white; -webkit-border-radius: 10px">
            </form>
        </div>
    </body>
</html>

users/templates/users/courses.html
{% extends "users/base.html" %}
{% block title %}
Courses
{% endblock %}
{% block content %}
<table style="width:50%; border-collapse:collapse; margin-left:auto; margin-right:auto">
    <caption style="text-align:center; font-size:xx-large">COURSES</caption>
    <thead>
        <th style="background-color: grey; color: white; text-align:left">NAME</th>
        <th style="background-color: grey; color: white; text-align:left">CODE</th>
    </thead>
    <tbody>
        {% for course in Courses %}
            <tr>
                <td style="border-bottom: 1px solid black;">{{course.0}}</td>
                <td style="border-bottom: 1px solid black;">{{course.1}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
{% block footer %}
{% endblock %}

users/templates/users/create_user.html
<html>
    <head>
        <script type="text/javascript" src="/media/jquery-3.0.0.min.js"></script>
        <script type="text/javascript" src="/media/main.js"></script>            
        <title>
            Create User
        </title>
    </head>
    <body>
        <div style="width:100%; text-align:center">
            <input id="message" style="float:right; -webkit-border-radius: 10px; border-color:green; color:green" value="User crested successfully">
            <a href="{% url 'users:users'%}" style="float:left"><img src="/media/back-icon.png"></a>
            <span style="font-size:xx-large;">Create User</span>
            <form action='http://127.0.0.1:8000/users/create/' style="" id="create_form">
                {% csrf_token %}
                Name:<br>
                <input type="text" name="name" style="-webkit-border-radius: 10px;" pattern="[A-Za-z]+" oninput="this.setCustomValidity('')" oninvalid="this.setCustomValidity('This is required field. Only alphabetical symbols are allowed')" required>
                <br>
                E-Mail:<br>
                <input type="email" name="email" style="-webkit-border-radius: 10px;" oninput="this.setCustomValidity('')" oninvalid="this.setCustomValidity('This is required field. Email should be correct (example: aaa@fdd.com)')" required>
                <br>
                Phone:<br>
                <input type="text" name="phone" style="-webkit-border-radius: 10px;" pattern="380\d{9}" oninput="this.setCustomValidity('')" oninvalid="this.setCustomValidity('Invalid number. Example 3080925057633')">
                <br>
                Mobilephone:<br>
                <input type="text" name="mobilephone" style="-webkit-border-radius: 10px;" pattern="380\d{9}" oninput="this.setCustomValidity('')" oninvalid="this.setCustomValidity('Invalid number. Example 3080925057633')">
                <br>
                Status:<br>
                <select name="status">
                    <option>Inactive</option>
                    <option>Active</option>
                </select>
                <br>
                <input type="submit" value="Create" style="background-color: green; color: white; -webkit-border-radius: 10px">
            </form>
        </div>
    </body>
</html>

users/templates/users/users.html
{% extends "users/base.html" %}
{%block title%}
Users
{%endblock%}
{% block content %}
<script>
    var elements_num = {{num_of_elements}};
</script>
<table style="width:50%; margin-left:auto; margin-right:auto">
    <caption>
    <div style="width:100%; text-align:center">
        <a href="{%url 'users:create' %}" style="display:inline-block; float:left"><img title="Add User" src="/media/add-icon.png"></a> 
        <form method="get" action="{%url 'users:users'%}" style="display:inline-block; float:left">
            <input type="hidden" name="page" value="{{curr_page}}">
            <input type="hidden" name="num_of_pages" value="{{num_of_elements}}">
            <input type="submit" style="background: url('/media/search-button.png'); border: 0; width:40; height:40" value="" alt="Search" title="Search"><input name="name"  type="text" style="-webkit-border-radius: 10px;">
        </form>
        <span style="display:inline-block; font-size: xx-large; float:left">Users</span>
        <select id="sel" style="float: right; -webkit-border-radius: 10px; background-color: white; color:black; display:inline-block" onchange="change_elements_number(this, {{curr_page}})">
            <option value="1">1</option>
            <option value="3">3</option>
        </select>
    </div>
    <caption>
    <thead>
        <th style="background-color:grey; color:white; text-align:left">NAME</th>
        <th style="background-color:grey; color:white; text-align:left">E-MAIL</th>
        <th style="background-color:grey; color:white; text-align:left">STATUS</th>
        <th style="background-color:grey; color:white; text-align:left">ACTION</th>
    <thead>
    <tbody>
        {% for user in Users%}
        <tr id={{user.0}}>
            <td style="border-bottom: 1px solid black;">{{user.1}}</td>
            <td style="border-bottom: 1px solid black;">{{user.2}}</td>
            <td style="border-bottom: 1px solid black;">{{user.5}}</td>
            <td style="border-bottom: 1px solid black;">
                <a href="http://127.0.0.1:8000/users/change/?user_id={{user.0}}"><img alt="Edit User" title="Edit User" src="/media/edit-icon.png"></a>
                <a href="#" id="delete_user" onclick="delete_f({{user.0}}, this)"><img alt="Delete User" title="Delete User" src="/media/delete-icon.png"></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
{% block footer %}
    <div style="width: 30%; margin:0 auto; text-align:center">
    <ul class="pagination pag-circle" style="">
        <li><a href="#" id="prev" onclick="prev_next_page(this, {{num_of_pages}}, {{curr_page}}, {{num_of_elements}})"><i class="material-icons"><<</i></a></li>
        {% for page in pages %}
        {% if page == curr_page %}
            <li><a href="http://127.0.0.1:8000/users/?page={{page}}&num_of_elements={{num_of_elements}}" id="{{page}}" style="color:white; background-color:grey">{{page}}</a></li>
        {% else %}
            <li><a href="http://127.0.0.1:8000/users/?page={{page}}&num_of_elements={{num_of_elements}}" id="{{page}}">{{page}}</a></li>
        {% endif %}
        {% endfor %}
        <li><a href="#" id="next" onclick="prev_next_page(this, {{num_of_pages}}, {{curr_page}}, {{num_of_elements}})"><i class="material-icons">>></i></a></li>
    </ul>
    </div>
{% endblock %}